package com.me4hik.praktika.ui.tour

import com.me4hik.praktika.R
import com.me4hik.praktika.navigation.Routes

/** Experimental CORE V1 training tour (27 steps, no Q/A cycle). */
object ExperimentalCoreTourV1 {
    const val DEFINITION_ID = "experimental_core_v1"

    val definition: TourDefinition = TourDefinition(
        id = DEFINITION_ID,
        steps = listOf(
            TourStep(
                id = TourStepId.START_INTRO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_start_intro,
                shortTitleResId = R.string.tour_title_start_intro,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.GO_HOME,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_home_intro,
                shortTitleResId = R.string.tour_title_home_overview,
                expectedRoutePrefix = Routes.HOME,
                onEnterNav = TourNavAction.POP_TO_HOME,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.HOME_STATUS,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_home_status,
                shortTitleResId = R.string.tour_title_home_status,
                targetId = TourTargetId.HOME_STATUS,
                expectedRoutePrefix = Routes.HOME,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.CLICK_ARCHIVE,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_click_archive,
                shortTitleResId = R.string.tour_title_click_archive,
                targetId = TourTargetId.HOME_ARCHIVE,
                expectedRoutePrefix = Routes.HOME,
                completion = TourCompletion.RouteMatch(Routes.ARCHIVE),
                onSkipNav = TourNavAction.NAVIGATE_ARCHIVE,
            ),
            TourStep(
                id = TourStepId.ARCHIVE_HUB_INTRO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_archive_hub,
                shortTitleResId = R.string.tour_title_archive_hub,
                targetId = TourTargetId.ARCHIVE_HUB,
                expectedRoutePrefix = Routes.ARCHIVE,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.CLICK_ARCHIVE_DAYS,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_click_archive_days,
                shortTitleResId = R.string.tour_title_click_archive_days,
                targetId = TourTargetId.ARCHIVE_OPEN_DAYS,
                expectedRoutePrefix = Routes.ARCHIVE,
                completion = TourCompletion.RouteMatch(Routes.ARCHIVE_DAYS),
                onSkipNav = TourNavAction.NAVIGATE_ARCHIVE_DAYS,
            ),
            TourStep(
                id = TourStepId.ARCHIVE_DAYS_CONTENT,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_archive_days_content,
                shortTitleResId = R.string.tour_title_archive_days_content,
                targetId = TourTargetId.ARCHIVE_DAYS_CONTENT,
                expectedRoutePrefix = Routes.ARCHIVE_DAYS,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.BACK_FROM_DAYS,
                type = TourStepType.NAV_BACK,
                tipResId = R.string.tour_step_back_from_days,
                shortTitleResId = R.string.tour_title_back_from_days,
                targetId = TourTargetId.ARCHIVE_BACK,
                expectedRoutePrefix = Routes.ARCHIVE_DAYS,
                completion = TourCompletion.LeftRoute(Routes.ARCHIVE_DAYS),
                onSkipNav = TourNavAction.POP_ONCE,
            ),
            TourStep(
                id = TourStepId.CLICK_EXPORT_ACCORDION,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_click_export_accordion,
                shortTitleResId = R.string.tour_title_click_export_accordion,
                targetId = TourTargetId.ARCHIVE_EXPORT_ACCORDION,
                expectedRoutePrefix = Routes.ARCHIVE,
                completion = TourCompletion.TargetActivation,
            ),
            TourStep(
                id = TourStepId.EXPORT_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_export_info,
                shortTitleResId = R.string.tour_title_export_info,
                targetId = TourTargetId.ARCHIVE_EXPORT_SECTION,
                expectedRoutePrefix = Routes.ARCHIVE,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.SHARE_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_share_info,
                shortTitleResId = R.string.tour_title_share_info,
                targetId = TourTargetId.ARCHIVE_SHARE_SECTION,
                expectedRoutePrefix = Routes.ARCHIVE,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.BACK_FROM_ARCHIVE,
                type = TourStepType.NAV_BACK,
                tipResId = R.string.tour_step_back_from_archive,
                shortTitleResId = R.string.tour_title_back_from_archive,
                targetId = TourTargetId.ARCHIVE_BACK,
                expectedRoutePrefix = Routes.ARCHIVE,
                completion = TourCompletion.LeftRoute(Routes.ARCHIVE),
                onSkipNav = TourNavAction.POP_TO_HOME,
            ),
            TourStep(
                id = TourStepId.CLICK_SETTINGS,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_click_settings,
                shortTitleResId = R.string.tour_title_click_settings,
                targetId = TourTargetId.HOME_SETTINGS,
                expectedRoutePrefix = Routes.HOME,
                completion = TourCompletion.RouteMatch(Routes.SETTINGS),
                onSkipNav = TourNavAction.NAVIGATE_SETTINGS,
            ),
            TourStep(
                id = TourStepId.SCHEDULE_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_schedule_info,
                shortTitleResId = R.string.tour_title_schedule_info,
                targetId = TourTargetId.SETTINGS_SCHEDULE,
                expectedRoutePrefix = Routes.SETTINGS,
                completion = TourCompletion.ManualAdvance,
                allowScroll = true,
                bringIntoView = true,
            ),
            TourStep(
                id = TourStepId.CHOOSE_WORDING,
                type = TourStepType.USER_CHOICE,
                tipResId = R.string.tour_step_choose_wording,
                shortTitleResId = R.string.tour_title_choose_wording,
                targetId = TourTargetId.SETTINGS_WORDING,
                expectedRoutePrefix = Routes.SETTINGS,
                completion = TourCompletion.TargetActivation,
                allowScroll = true,
                bringIntoView = true,
            ),
            TourStep(
                id = TourStepId.PAUSE_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_pause_info,
                shortTitleResId = R.string.tour_title_pause_info,
                targetId = TourTargetId.SETTINGS_PAUSE,
                expectedRoutePrefix = Routes.SETTINGS,
                completion = TourCompletion.ManualAdvance,
                allowScroll = true,
                bringIntoView = true,
            ),
            TourStep(
                id = TourStepId.BACKUP_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_backup_info,
                shortTitleResId = R.string.tour_title_backup_info,
                targetId = TourTargetId.SETTINGS_BACKUP,
                expectedRoutePrefix = Routes.SETTINGS,
                completion = TourCompletion.ManualAdvance,
                allowScroll = true,
                bringIntoView = true,
            ),
            TourStep(
                id = TourStepId.CLICK_NOTIFICATIONS,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_click_notifications,
                shortTitleResId = R.string.tour_title_click_notifications,
                targetId = TourTargetId.SETTINGS_NOTIFICATIONS,
                expectedRoutePrefix = Routes.SETTINGS,
                completion = TourCompletion.RouteMatch(Routes.SETTINGS_NOTIFICATIONS),
                allowScroll = true,
                bringIntoView = true,
                onSkipNav = TourNavAction.NAVIGATE_NOTIFICATIONS,
            ),
            TourStep(
                id = TourStepId.SOUND_SWITCH_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_sound_switch_info,
                shortTitleResId = R.string.tour_title_sound_switch_info,
                targetId = TourTargetId.NOTIFICATIONS_SOUND_SWITCH,
                expectedRoutePrefix = Routes.SETTINGS_NOTIFICATIONS,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.CLICK_SOUND_LIBRARY,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_click_sound_library,
                shortTitleResId = R.string.tour_title_click_sound_library,
                targetId = TourTargetId.NOTIFICATIONS_SOUND_LIBRARY,
                expectedRoutePrefix = Routes.SETTINGS_NOTIFICATIONS,
                completion = TourCompletion.RouteMatch(Routes.SOUND_LIBRARY),
                onSkipNav = TourNavAction.NAVIGATE_SOUND_LIBRARY,
            ),
            TourStep(
                id = TourStepId.PREVIEW_SOUND,
                type = TourStepType.TARGET_CLICK,
                tipResId = R.string.tour_step_preview_sound,
                shortTitleResId = R.string.tour_title_preview_sound,
                targetId = TourTargetId.SOUND_LIBRARY_FIRST_VISIBLE_BUILTIN_PLAY,
                expectedRoutePrefix = Routes.SOUND_LIBRARY,
                completion = TourCompletion.TargetActivation,
            ),
            TourStep(
                id = TourStepId.CHOOSE_SOUND,
                type = TourStepType.USER_CHOICE,
                tipResId = R.string.tour_step_choose_sound,
                shortTitleResId = R.string.tour_title_choose_sound,
                targetId = TourTargetId.SOUND_LIBRARY_FIRST_VISIBLE_BUILTIN_ITEM,
                expectedRoutePrefix = Routes.SOUND_LIBRARY,
                completion = TourCompletion.TargetActivation,
            ),
            TourStep(
                id = TourStepId.HIDE_RESTORE_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_hide_restore_info,
                shortTitleResId = R.string.tour_title_hide_restore_info,
                targetId = TourTargetId.SOUND_HIDE_RESTORE_INFO,
                expectedRoutePrefix = Routes.SOUND_LIBRARY,
                completion = TourCompletion.ManualAdvance,
            ),
            TourStep(
                id = TourStepId.BACK_FROM_SOUND,
                type = TourStepType.NAV_BACK,
                tipResId = R.string.tour_step_back_from_sound,
                shortTitleResId = R.string.tour_title_back_from_sound,
                targetId = TourTargetId.SOUND_LIBRARY_BACK,
                expectedRoutePrefix = Routes.SOUND_LIBRARY,
                completion = TourCompletion.LeftRoute(Routes.SOUND_LIBRARY),
                onSkipNav = TourNavAction.POP_ONCE,
            ),
            TourStep(
                id = TourStepId.CHOOSE_DEFER,
                type = TourStepType.USER_CHOICE,
                tipResId = R.string.tour_step_choose_defer,
                shortTitleResId = R.string.tour_title_choose_defer,
                targetId = TourTargetId.NOTIFICATIONS_DEFER,
                expectedRoutePrefix = Routes.SETTINGS_NOTIFICATIONS,
                completion = TourCompletion.TargetActivation,
                allowScroll = true,
                bringIntoView = true,
            ),
            TourStep(
                id = TourStepId.SYSTEM_NOTIFICATIONS_INFO,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_system_notifications,
                shortTitleResId = R.string.tour_title_system_notifications,
                targetId = TourTargetId.NOTIFICATIONS_SYSTEM_SETTINGS,
                expectedRoutePrefix = Routes.SETTINGS_NOTIFICATIONS,
                completion = TourCompletion.ManualAdvance,
                allowScroll = true,
                bringIntoView = true,
            ),
            TourStep(
                id = TourStepId.FINISHED,
                type = TourStepType.SHOW_ONLY,
                tipResId = R.string.tour_step_finished,
                shortTitleResId = R.string.tour_title_finished,
                completion = TourCompletion.ManualAdvance,
            ),
        ),
    )
}

/** Compatibility alias for older call sites / tests. */
object ExperimentalVerticalSliceTour {
    const val DEFINITION_ID = ExperimentalCoreTourV1.DEFINITION_ID
    val definition: TourDefinition get() = ExperimentalCoreTourV1.definition
}
