# 04.08.2026 Reminder App cursor by Me4Hik START - свойства Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.java.home=<JAVA_HOME>
# 04.08.2026 Reminder App cursor by Me4Hik END
